"""changed sox to so2

Revision ID: 7965aaa3e210
Revises: fc63f7f3c91d
Create Date: 2024-11-08 14:59:52.659971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7965aaa3e210'
down_revision = 'fc63f7f3c91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('so2', sa.Integer(), nullable=True))
        batch_op.drop_column('sox')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sox', sa.INTEGER(), nullable=True))
        batch_op.drop_column('so2')

    # ### end Alembic commands ###
