"""Add emissions per mwh

Revision ID: be0f9d85b238
Revises: 4808c5e49b79
Create Date: 2025-02-14 17:25:27.991641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0f9d85b238'
down_revision = '4808c5e49b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nox_per_mwh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('so2_per_mwh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('co2_per_mwh', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.drop_column('co2_per_mwh')
        batch_op.drop_column('so2_per_mwh')
        batch_op.drop_column('nox_per_mwh')

    # ### end Alembic commands ###
